// Default screen permissions per role (must stay in sync with seed.ts)
export const DEFAULT_PERMISSIONS: Record<string, string[]> = {
  system_admin: [
    'DASHBOARD_VIEW', 'ANALYTICS_VIEW', 'PHARMACY_MANAGE', 'USER_MANAGE', 'ROLE_MANAGE',
    'PRESCRIPTION_VIEW', 'PRESCRIPTION_REVIEW', 'INVENTORY_VIEW', 'INVENTORY_MANAGE',
    'ORDER_VIEW', 'ORDER_MANAGE', 'BILLING_VIEW', 'BILLING_MANAGE',
    'AI_PIPELINE_VIEW', 'DELIVERY_MANAGE', 'GRN_MANAGE', 'MEDICINE_MANAGE', 'REPORTS_VIEW',
  ],
  pharmacy_admin: [
    'DASHBOARD_VIEW', 'ANALYTICS_VIEW', 'USER_MANAGE', 'ROLE_MANAGE',
    'PRESCRIPTION_VIEW', 'PRESCRIPTION_REVIEW', 'INVENTORY_VIEW', 'INVENTORY_MANAGE',
    'ORDER_VIEW', 'ORDER_MANAGE', 'BILLING_VIEW', 'BILLING_MANAGE',
    'AI_PIPELINE_VIEW', 'DELIVERY_MANAGE', 'GRN_MANAGE', 'MEDICINE_MANAGE', 'REPORTS_VIEW',
  ],
  pharmacy_staff: [
    'DASHBOARD_VIEW', 'ANALYTICS_VIEW', 'PRESCRIPTION_VIEW', 'PRESCRIPTION_REVIEW',
    'INVENTORY_VIEW', 'INVENTORY_MANAGE', 'ORDER_VIEW', 'ORDER_MANAGE',
    'BILLING_VIEW', 'BILLING_MANAGE', 'AI_PIPELINE_VIEW', 'DELIVERY_MANAGE',
    'GRN_MANAGE', 'MEDICINE_MANAGE',
  ],
  customer: ['DASHBOARD_VIEW', 'ORDER_VIEW', 'PRESCRIPTION_VIEW'],
};
